apiVersion: v1
kind: Service
metadata:
  name: loop-gateway
  namespace: loop
  labels:
    app: loop-gateway
spec:
  type: ClusterIP
  selector:
    app: loop-gateway
  ports:
    - name: http
      port: 3001
      targetPort: 3001
