apiVersion: v1
kind: Service
metadata:
  name: loop-web
  namespace: loop
  labels:
    app: loop-web
spec:
  type: ClusterIP
  selector:
    app: loop-web
  ports:
    - name: http
      port: 3002
      targetPort: 3002
