import {
  CODEBASE_SUMMARY_REL_PATH,
  PROJECT_CACHE_DIR,
  type ProjectModelConfig,
} from '@loop/shared';
import { Injectable } from '@nestjs/common';
import { access, mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { ModelRouter } from '../model/model-router.js';
import { generateCodebaseSummary } from './summary-llm.js';
import { scanWorkspace } from './workspace-scanner.js';

interface SummaryMeta {
  gitRef: string;
  remoteUrl: string;
  generatedAt: string;
}

export interface EnsureSummaryInput {
  projectId: string;
  loopId: string;
  workspacePath: string;
  gitRef?: string;
  remoteUrl?: string;
  projectModelConfig?: ProjectModelConfig;
}

@Injectable()
export class CodebaseSummaryService {
  constructor(private readonly modelRouter: ModelRouter) {}

  isEnabled(): boolean {
    return process.env.CODEBASE_SUMMARY_ENABLED !== 'false';
  }

  summaryPath(workspacePath: string): string {
    return join(workspacePath, CODEBASE_SUMMARY_REL_PATH);
  }

  async hasSummary(workspacePath: string): Promise<boolean> {
    return this.pathExists(this.summaryPath(workspacePath));
  }

  private projectCacheDir(projectId: string): string {
    const root = process.env.WORKSPACE_ROOT ?? './workspaces';
    return join(root, PROJECT_CACHE_DIR, projectId);
  }

  private async pathExists(path: string): Promise<boolean> {
    try {
      await access(path);
      return true;
    } catch {
      return false;
    }
  }

  private async readMeta(cacheDir: string): Promise<SummaryMeta | null> {
    try {
      const raw = await readFile(join(cacheDir, 'meta.json'), 'utf-8');
      return JSON.parse(raw) as SummaryMeta;
    } catch {
      return null;
    }
  }

  private async writeSummary(targetPath: string, body: string, meta: {
    loopId: string;
    gitRef?: string;
    remoteUrl?: string;
    fromCache: boolean;
  }): Promise<void> {
    await mkdir(dirname(targetPath), { recursive: true });
    const header = [
      '<!-- AUTO-GENERATED BY LOOP ORCHESTRATOR — DO NOT COMMIT -->',
      `<!-- loop: ${meta.loopId} -->`,
      meta.gitRef ? `<!-- git-ref: ${meta.gitRef} -->` : '',
      meta.remoteUrl ? `<!-- remote: ${meta.remoteUrl} -->` : '',
      meta.fromCache ? '<!-- source: project-cache -->' : '<!-- source: llm -->',
      '',
    ]
      .filter(Boolean)
      .join('\n');

    await writeFile(targetPath, `${header}${body}\n`, 'utf-8');
    await writeFile(join(dirname(targetPath), '.gitignore'), '*\n', 'utf-8');
  }

  async ensureForLoop(input: EnsureSummaryInput): Promise<{ path: string; cached: boolean } | null> {
    if (!this.isEnabled()) return null;
    if (!input.remoteUrl) return null;

    const targetPath = this.summaryPath(input.workspacePath);
    const cacheDir = this.projectCacheDir(input.projectId);
    const cachePath = join(cacheDir, 'codebase-summary.md');
    const meta = await this.readMeta(cacheDir);

    const cacheValid =
      Boolean(input.gitRef) &&
      meta?.gitRef === input.gitRef &&
      meta?.remoteUrl === input.remoteUrl &&
      (await this.pathExists(cachePath));

    if (cacheValid) {
      await this.writeSummary(targetPath, await readFile(cachePath, 'utf-8'), {
        loopId: input.loopId,
        gitRef: input.gitRef,
        remoteUrl: input.remoteUrl,
        fromCache: true,
      });
      return { path: CODEBASE_SUMMARY_REL_PATH, cached: true };
    }

    const snapshot = await scanWorkspace(input.workspacePath);
    if (snapshot.keyFiles.length === 0 && snapshot.tree === '(empty workspace)') {
      return null;
    }

    const model = this.modelRouter.resolve(input.projectModelConfig, undefined, 'pm');
    const summaryBody = await generateCodebaseSummary(snapshot, model);

    await mkdir(cacheDir, { recursive: true });
    await writeFile(cachePath, summaryBody, 'utf-8');
    if (input.gitRef) {
      const metaOut: SummaryMeta = {
        gitRef: input.gitRef,
        remoteUrl: input.remoteUrl,
        generatedAt: new Date().toISOString(),
      };
      await writeFile(join(cacheDir, 'meta.json'), JSON.stringify(metaOut, null, 2), 'utf-8');
    }

    await this.writeSummary(targetPath, summaryBody, {
      loopId: input.loopId,
      gitRef: input.gitRef,
      remoteUrl: input.remoteUrl,
      fromCache: false,
    });

    return { path: CODEBASE_SUMMARY_REL_PATH, cached: false };
  }
}
