import {
  PROJECT_CACHE_DIR,
  PROJECT_LOOP_SUMMARIES_DIR,
  PROJECT_REQUIREMENTS_SUMMARY_FILE,
  type ProjectModelConfig,
} from '@loop/shared';
import { Injectable } from '@nestjs/common';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { ChatService } from '../chat/chat.service.js';
import { LoopRepository } from '../db/repositories/loop.repository.js';
import { ProjectRepository } from '../db/repositories/project.repository.js';
import { ModelRouter } from '../model/model-router.js';
import {
  generateLoopDeliverySummary,
  mergeProjectRequirementsSummary,
} from './requirements-summary-llm.js';

@Injectable()
export class RequirementsSummaryService {
  constructor(
    private readonly loopRepo: LoopRepository,
    private readonly projectRepo: ProjectRepository,
    private readonly modelRouter: ModelRouter,
    private readonly chatService: ChatService,
  ) {}

  isEnabled(): boolean {
    return process.env.REQUIREMENTS_SUMMARY_ENABLED !== 'false';
  }

  projectCacheDir(projectId: string): string {
    const root = process.env.WORKSPACE_ROOT ?? './workspaces';
    return join(root, PROJECT_CACHE_DIR, projectId);
  }

  async readProjectSummary(projectId: string): Promise<string | null> {
    if (!this.isEnabled()) return null;
    try {
      const raw = await readFile(
        join(this.projectCacheDir(projectId), PROJECT_REQUIREMENTS_SUMMARY_FILE),
        'utf-8',
      );
      return raw.replace(/^<!--[\s\S]*?-->\n*/m, '').trim() || null;
    } catch {
      return null;
    }
  }

  /** Loop 结束：生成本 Loop 总结并更新项目需求文档总结 */
  async finalizeLoop(loopId: string, completedBy?: string): Promise<void> {
    if (!this.isEnabled()) return;

    const loop = await this.loopRepo.findById(loopId);
    if (!loop) return;

    const project = await this.projectRepo.findById(loop.project_id);
    if (!project) return;

    this.chatService.emitProcessing({
      loopId,
      active: true,
      label: '正在生成本 Loop 总结并更新项目需求文档…',
    });

    try {
      const model = this.modelRouter.resolve(
        project.model_config as ProjectModelConfig,
        undefined,
        'pm',
      );

      const loopSummary = await generateLoopDeliverySummary({
        loopId: loop.id,
        loopTitle: loop.title,
        context: loop.context,
        model,
      });

      const cacheDir = this.projectCacheDir(loop.project_id);
      const loopsDir = join(cacheDir, PROJECT_LOOP_SUMMARIES_DIR);
      await mkdir(loopsDir, { recursive: true });

      const loopFileHeader = [
        '<!-- AUTO-GENERATED BY LOOP ORCHESTRATOR -->',
        `<!-- loop: ${loopId} -->`,
        `<!-- completedAt: ${new Date().toISOString()} -->`,
        '',
      ].join('\n');

      await writeFile(
        join(loopsDir, `${loopId}.md`),
        `${loopFileHeader}${loopSummary}\n`,
        'utf-8',
      );

      const existing = await this.readProjectSummary(loop.project_id);
      const merged = await mergeProjectRequirementsSummary({
        projectName: project.name,
        existingSummary: existing,
        loopId: loop.id,
        loopTitle: loop.title,
        loopSummary,
        model,
      });

      await mkdir(cacheDir, { recursive: true });
      const projectHeader = [
        '<!-- AUTO-GENERATED BY LOOP ORCHESTRATOR — 项目需求文档总结 -->',
        `<!-- updatedAt: ${new Date().toISOString()} -->`,
        `<!-- lastLoop: ${loopId} -->`,
        '',
      ].join('\n');
      await writeFile(
        join(cacheDir, PROJECT_REQUIREMENTS_SUMMARY_FILE),
        `${projectHeader}${merged}\n`,
        'utf-8',
      );

      await this.chatService.publishAgentMessage({
        loopId,
        phase: 'done',
        agentId: 'orchestrator',
        content: {
          type: 'artifact',
          body: [
            '## 项目需求文档总结已更新',
            '',
            `本 Loop（\`${loop.title}\`）的交付总结已写入项目知识库，供后续 Loop 的 PM Agent 参考。`,
            '',
            '### 本 Loop 交付摘要',
            loopSummary.length > 600 ? `${loopSummary.slice(0, 600)}…` : loopSummary,
            '',
            `完整项目总结路径：\`_project-cache/${loop.project_id}/${PROJECT_REQUIREMENTS_SUMMARY_FILE}\``,
            completedBy ? `\n由 @${completedBy} 确认流水线完成时自动生成。` : '',
          ].join('\n'),
        },
      });
    } catch (err) {
      console.warn(`[requirements-summary] finalize failed for ${loopId}:`, err);
      const msg = err instanceof Error ? err.message : String(err);
      await this.chatService.publishAgentMessage({
        loopId,
        phase: 'done',
        agentId: 'orchestrator',
        content: {
          type: 'text',
          body: `项目需求文档总结更新失败（${msg}），不影响 Loop 完成。可稍后重试或人工维护。`,
        },
      });
    } finally {
      this.chatService.emitProcessing({ loopId, active: false });
    }
  }
}
